In [1]:
import os
from tqdm import tqdm
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt
from matplotlib.lines import Line2D
import matplotlib.font_manager as font_manager
font_manager.fontManager.addfont("/home/tx82/Arial.ttf")
plt.rcParams['font.family'] = 'Arial'
import matplotlib.ticker as mticker
from scipy.stats import mannwhitneyu
from itertools import combinations

In [2]:
root_dir = "/fs/cbsuhy02/storage/tx82/"

In [3]:
# load gene table (protein coding genes, using gencode v46 annotation)
gene_table_file = os.path.join(root_dir, "_DATA/_COMMON/_reference/gencode/gencode.v46.annotation.coding.tsv")
gene_table = pd.read_table(gene_table_file)
print("Number of all protein coding genes:", len(gene_table["gene_name"].unique()))

# load metadata and id-mapping (UniProt to gene name)
df_annot = pd.read_csv(os.path.join(root_dir, "_DATA/_COMMON/_reference/HUMAN_9606_idmapping.dat.gz"), sep = "\t", dtype = str, header = None)
df_annot[0] = df_annot[0].apply(lambda x: x.split("-")[0])
df_annot[2] = df_annot[2].apply(lambda x: x.split(".")[0])
df_annot = df_annot[[0, 2]].drop_duplicates().rename(columns = {0: "UniProt"})

# filter the id_mapping file by gene names from the gene table
id_mapping = df_annot[df_annot[2].isin(list(gene_table["gene_name"]))]
id_mapping = id_mapping.rename(columns={2: "gene_name"})
id_mapping.head()

Number of all protein coding genes: 20036

    UniProt gene_name
1    P31946     YWHAB
118  P62258     YWHAE
246  Q04917     YWHAH
336  P61981     YWHAG
462  P31947       SFN

In [ ]:
## Merge and process HINT lists

def fill_gene_name(gene_orig, gene_mapped): 
    # if there is a gene_name in the HINT, then use the original gene_name, otherwise mapped with the gene_name in the idmapping
    # !! but the original gene names in HINT might not be the approved symbols 
    if pd.isna(gene_orig) == False:
        return gene_orig
    else:
        return gene_mapped
    
# concatenate interactomes (downloaded from HINT)
HINT_file_list = ["HomoSapiens_cocomp_all.txt", "HomoSapiens_binary_all.txt"]
HINT_interactomes = []
for HINT_file in HINT_file_list:
    HINT_file_path = os.path.join(root_dir, "_DATA/_COMMON/network/HINT/", HINT_file)
    interactome = pd.read_table(HINT_file_path)
    tqdm.pandas()
    interactome["Uniprot_A"] = interactome["Uniprot_A"].apply(lambda x: x.split("-")[0]) # ignore isoforms
    interactome["Uniprot_B"] = interactome["Uniprot_B"].apply(lambda x: x.split("-")[0]) # ignore isoforms
    interactome = interactome[interactome["Uniprot_A"] != interactome["Uniprot_B"]] # remove self_loop
    interactome["PPI_pair"] = interactome.progress_apply(lambda row: ":".join(sorted([row["Uniprot_A"],row["Uniprot_B"]])), axis=1) # sorted PPI pairs
    interactome = interactome.drop_duplicates(subset=["PPI_pair"])
    # display(interactome.head())
    HINT_interactomes.append(interactome)
HINT_all_interactome = pd.concat(HINT_interactomes, axis=0)
HINT_all_interactome = HINT_all_interactome.drop_duplicates(subset=["PPI_pair"])
HINT_all_interactome = HINT_all_interactome[["Uniprot_A", "Uniprot_B", "PPI_pair", "Gene_A", "Gene_B"]]

# map uniprot IDs to gene names using id-mapping, and fill gene names (if NA in HINT then use mapped gene names, if have the original names in HINT then use the riginal names)
HINT_all_interactome = pd.merge(HINT_all_interactome, id_mapping, left_on="Uniprot_A", right_on="UniProt", how="left").rename(columns={"gene_name": "Gene_name_A"}).drop(columns=["UniProt"])
HINT_all_interactome = pd.merge(HINT_all_interactome, id_mapping, left_on="Uniprot_B", right_on="UniProt", how="left").rename(columns={"gene_name": "Gene_name_B"}).drop(columns=["UniProt"])
HINT_all_interactome["Gene_filled_A"] = HINT_all_interactome.progress_apply(lambda row: fill_gene_name(row["Gene_A"], row["Gene_name_A"]), axis=1)
HINT_all_interactome["Gene_filled_B"] = HINT_all_interactome.progress_apply(lambda row: fill_gene_name(row["Gene_B"], row["Gene_name_B"]), axis=1)

# use the mapped and clean gene names to generate gene pairs
HINT_all_interactome = HINT_all_interactome[["Uniprot_A", "Uniprot_B", "PPI_pair", "Gene_filled_A", "Gene_filled_B"]]
HINT_all_interactome = HINT_all_interactome.dropna(how="any")
HINT_all_interactome["gene_pair"] = HINT_all_interactome.apply(lambda row: ":".join(sorted([row["Gene_filled_A"], row["Gene_filled_B"]])), axis=1)
HINT_all_interactome = HINT_all_interactome.drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)

# !! Issue: but many original gene names in HINT are not the approved HGNC symbols, need to map them to the approved symbols

# # generate the gene list for those genes that are not approved HGNC symbols
# hgnc_gene_info = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/genes/HGNC_symbols/HGNC_proteincoding.txt"))
# HINT_all_interactome_genes = pd.DataFrame(list(set(list(HINT_all_interactome["Gene_filled_A"].unique()) + list(HINT_all_interactome["Gene_filled_B"].unique()))))
# HINT_all_interactome_genes[~HINT_all_interactome_genes[0].isin(list(hgnc_gene_info["symbol"]))].to_csv(os.path.join(root_dir, "_DATA/_COMMON/network/HINT/HomoSapiens_both_all_genes_notapproved.txt"), sep='\t', index=None, header=None)

# load the appoved HGNC mapping only for those genes that are not approved symbols (converted from the HGNC website, see the file "HomoSapiens_both_all_genes_notapproved_hgnc.csv")
HINT_all_notapproved_baits_genes_hgnc = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/HINT/HomoSapiens_both_all_genes_notapproved_hgnc.csv"), sep=',')
genes_approved = []
for input_gene in HINT_all_notapproved_baits_genes_hgnc["Input"].unique():
    hgnc_inputgene = HINT_all_notapproved_baits_genes_hgnc[HINT_all_notapproved_baits_genes_hgnc["Input"] == input_gene]
    hgnc_inputgene_appr = hgnc_inputgene[hgnc_inputgene["Match type"] == "Approved symbol"]
    if len(hgnc_inputgene_appr) == 0: # for input genes that are not approved HGNC symbols, replace with all the mapped approved symbols
        print("Not the approved symbol:", input_gene)
        # display(hgnc_inputgene)
        genes_approved.append(hgnc_inputgene[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) == 1:
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) > 1:
        # display(genes_hgnc_inputgene_apr)
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
genes_approved = pd.concat(genes_approved, axis=0).reset_index(drop=True)
display(genes_approved.head())

# finally, using the clean, filled and mostly approved symbols as gene names to generate gene_pairs and filter out duplicated ones
HINT_all_interactome = pd.merge(HINT_all_interactome, genes_approved, left_on="Gene_filled_A", right_on="Input", how="left").rename(columns={"Approved symbol":"Gene_approved_A"}).drop(columns=["Input"])
HINT_all_interactome["Gene_approved_A"] = HINT_all_interactome.apply(lambda row: row["Gene_approved_A"] if pd.isna(row["Gene_approved_A"]) == False else row["Gene_filled_A"], axis=1) # if no approved symbol, just use the original one
HINT_all_interactome = pd.merge(HINT_all_interactome, genes_approved, left_on="Gene_filled_B", right_on="Input", how="left").rename(columns={"Approved symbol":"Gene_approved_B"}).drop(columns=["Input"])
HINT_all_interactome["Gene_approved_B"] = HINT_all_interactome.apply(lambda row: row["Gene_approved_B"] if pd.isna(row["Gene_approved_B"]) == False else row["Gene_filled_B"], axis=1) # if no approved symbol, just use the original one
HINT_all_interactome["gene_pair"] = HINT_all_interactome.apply(lambda row: ":".join(sorted([row["Gene_approved_A"], row["Gene_approved_B"]])), axis=1)
HINT_all_interactome = HINT_all_interactome.drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)
HINT_all_interactome = HINT_all_interactome[["Uniprot_A", "Uniprot_B", "PPI_pair", "Gene_approved_A", "Gene_approved_B", "gene_pair"]]

# save the merged interactome with filled gene names and approved symbols, and the gene pairs with approved symbols
HINT_all_interactome_file = os.path.join(root_dir, "_DATA/_COMMON/network/HINT/HomoSapiens_both_all.txt")
HINT_all_interactome.to_csv(HINT_all_interactome_file, sep='\t', index=None)
print("Number of interactions:", len(HINT_all_interactome))
HINT_all_interactome.head()

100%|██████████| 605110/605110 [00:03<00:00, 178914.43it/s]
100%|██████████| 484734/484734 [00:02<00:00, 182937.02it/s]
100%|██████████| 851183/851183 [00:04<00:00, 187244.71it/s]
100%|██████████| 851183/851183 [00:04<00:00, 177953.80it/s]

Not the approved symbol: LOC554223
Not the approved symbol: CEFIP
Not the approved symbol: MUXA
Not the approved symbol: HEL-S-123m
Not the approved symbol: C16orf35
Not the approved symbol: RAB7L1
Not the approved symbol: BPGF-1
Not the approved symbol: NR1A2
Not the approved symbol: HEL-S-72p
Not the approved symbol: HEL-S-97n
Not the approved symbol: LOC51064
Not the approved symbol: C1orf19
Not the approved symbol: URCC5
Not the approved symbol: YARS
Not the approved symbol: IL-6SAG
Not the approved symbol: G7
Not the approved symbol: ARHH
Not the approved symbol: L27a
Not the approved symbol: SEPT3
Not the approved symbol: TC4
Not the approved symbol: GAPD
Not the approved symbol: PRR10
Not the approved symbol: TGIF2-C20orf24
Not the approved symbol: C5orf64
Not the approved symbol: MGC50722
Not the approved symbol: LOC392787
Not the approved symbol: HIST1H4L
Not the approved symbol: CCDC113
Not the approved symbol: NPEPPSL1
Not the approved symbol: FLJ11292
Not the approved symbol: ASCC3L1
Not the approved symbol: HEL-S-101
Not the approved symbol: C2orf48
Not the approved symbol: EPR-1
Not the approved symbol: SNX26
Not the approved symbol: ZC3HDC1
Not the approved symbol: C21orf29
Not the approved symbol: ADAL
Not the approved symbol: OK/KNS-cl.4
Not the approved symbol: hCG_1820408
Not the approved symbol: CHLR1
Not the approved symbol: SMP1
Not the approved symbol: ATP5B
Not the approved symbol: EIF2C2
Not the approved symbol: HEL-S-2a
Not the approved symbol: DKFZp781O1323
Not the approved symbol: hTIM44
Not the approved symbol: CRSP9
Not the approved symbol: HEL-S-29
Not the approved symbol: ENSG00000266997
Not the approved symbol: CCM1
Not the approved symbol: ENSG00000286905
Not the approved symbol: ENSG00000284292
Not the approved symbol: ENSG00000255432
Not the approved symbol: ZNF
Not the approved symbol: NR1C1
Not the approved symbol: NR2A2
Not the approved symbol: DKFZp761B2210
Not the approved symbol: ANKRD13
Not the approved symbol: HNRPK
Not the approved symbol: SARG
Not the approved symbol: HNRPM
Not the approved symbol: DKFZp762F2011
Not the approved symbol: FLJ10404
Not the approved symbol: G4
Not the approved symbol: FLJ23584
Not the approved symbol: DKFZp686J08252
Not the approved symbol: DKFZp667L0421
Not the approved symbol: DKFZp547K2416
Not the approved symbol: HSP70-1
Not the approved symbol: MTGR1
Not the approved symbol: HEL-S-182mP
Not the approved symbol: DKFZp686O0870
Not the approved symbol: p14ARF
Not the approved symbol: DKFZp686P0251
Not the approved symbol: ENSG00000244255
Not the approved symbol: MUM1
Not the approved symbol: CASC5
Not the approved symbol: M-RIP
Not the approved symbol: HCC5
Not the approved symbol: HEL-S-77p
Not the approved symbol: BCE1
Not the approved symbol: HEL-S-5
Not the approved symbol: LOC200261
Not the approved symbol: KIAA1984
Not the approved symbol: HIST1H2AK
Not the approved symbol: DKFZp451O0517
Not the approved symbol: DKFZp451F1115
Not the approved symbol: ARP3BETA
Not the approved symbol: HEL25
Not the approved symbol: HEL-S-1
Not the approved symbol: HEL-S-67p
Not the approved symbol: LOC57228
Not the approved symbol: ND1
Not the approved symbol: MLL
Not the approved symbol: SLC22A18
Not the approved symbol: DNCI1
Not the approved symbol: C14orf133
Not the approved symbol: HEL-S-30
Not the approved symbol: C1orf131
Not the approved symbol: PEX26T35insC
Not the approved symbol: EFHA1
Not the approved symbol: CCDC65
Not the approved symbol: B9838V1
Not the approved symbol: ADFP
Not the approved symbol: CYRN2
Not the approved symbol: DKFZp686N0561
Not the approved symbol: TSSK1
Not the approved symbol: DKFZp686H10254
Not the approved symbol: ENSG00000280571
Not the approved symbol: CIR1
Not the approved symbol: H3F3AP6
Not the approved symbol: hCG_2001421
Not the approved symbol: DKFZp667H197
Not the approved symbol: IQCG
Not the approved symbol: DKFZp686I15212
Not the approved symbol: HEL-S-90n
Not the approved symbol: RP11-311P8.3
Not the approved symbol: hCG_1811444
Not the approved symbol: BXDC2
Not the approved symbol: C9orf75
Not the approved symbol: DNCL1
Not the approved symbol: HEL-S-47e
Not the approved symbol: KNTC2
Not the approved symbol: NEF3
Not the approved symbol: CNK3/IPCEF1
Not the approved symbol: PCTK3
Not the approved symbol: DKFZp434J046
Not the approved symbol: DKFZp686J1568
Not the approved symbol: U5-116KD
Not the approved symbol: C4orf19
Not the approved symbol: ENSG00000263809
Not the approved symbol: LPPR4
Not the approved symbol: tmp_locus_54
Not the approved symbol: RUVBL
Not the approved symbol: NR3B3
Not the approved symbol: HEL-S-91n
Not the approved symbol: DKFZp761H172
Not the approved symbol: DKFZp686P17171
Not the approved symbol: CCDC103
Not the approved symbol: DKFZp586M1819
Not the approved symbol: FLJ00321
Not the approved symbol: HEL-S-103
Not the approved symbol: TCTE1
Not the approved symbol: SYT-SSX2
Not the approved symbol: PRPF4B
Not the approved symbol: FAM127B
Not the approved symbol: GOLPH2
Not the approved symbol: PAPD5
Not the approved symbol: derp12
Not the approved symbol: BPGAP1
Not the approved symbol: CTGF
Not the approved symbol: GPR182
Not the approved symbol: ENSG00000260342
Not the approved symbol: hCG_1998195
Not the approved symbol: MKL1
Not the approved symbol: SFRS3
Not the approved symbol: DKFZp686P11128
Not the approved symbol: DYR
Not the approved symbol: HPH2
Not the approved symbol: ENSG00000269547
Not the approved symbol: AID
Not the approved symbol: ORC1L
Not the approved symbol: HMP19
Not the approved symbol: HEL-S-42
Not the approved symbol: ENSG00000250644
Not the approved symbol: DKFZp686P15220
Not the approved symbol: HLA-A*03
Not the approved symbol: HEL-S-95n
Not the approved symbol: ZF6
Not the approved symbol: BMT2
Not the approved symbol: C10orf104
Not the approved symbol: NMES1
Not the approved symbol: MGC39372
Not the approved symbol: SELI
Not the approved symbol: hCG_20425
Not the approved symbol: DKFZp686J1593
Not the approved symbol: ENSG00000257390
Not the approved symbol: WUGSC:H_DJ0726N20.gs.b
Not the approved symbol: GIG44
Not the approved symbol: TRY8
Not the approved symbol: DKFZp686L18142
Not the approved symbol: BAK
Not the approved symbol: ZNF509
Not the approved symbol: ATP5H
Not the approved symbol: ND6
Not the approved symbol: C3orf60
Not the approved symbol: C15orf38-AP3S2
Not the approved symbol: SRPR
Not the approved symbol: LOC554248
Not the approved symbol: ENSG00000255439
Not the approved symbol: WUGSC:H_RG054D04.1
Not the approved symbol: MSL3P1
Not the approved symbol: DKFZp434F0116
Not the approved symbol: HIST1H4H
Not the approved symbol: DKFZp434N1728
Not the approved symbol: C6orf226
Not the approved symbol: CYTSA
Not the approved symbol: CCDC153
Not the approved symbol: urf-ret
Not the approved symbol: CABL1
Not the approved symbol: FIMP
Not the approved symbol: NFI
Not the approved symbol: ENSG00000271793
Not the approved symbol: SPO16
Not the approved symbol: RQCD1
Not the approved symbol: TWEAK
Not the approved symbol: C10orf2
Not the approved symbol: MST4
Not the approved symbol: HEL-S-130P
Not the approved symbol: PIG59
Not the approved symbol: RICS
Not the approved symbol: NRAC
Not the approved symbol: C2orf27A
Not the approved symbol: LOC402287
Not the approved symbol: NR2B3
Not the approved symbol: MENT
Not the approved symbol: HEL-S-99n
Not the approved symbol: OCC1
Not the approved symbol: SYT-SSX1
Not the approved symbol: DKFZp686M24262
Not the approved symbol: DKFZp781I1140
Not the approved symbol: KIAA0100
Not the approved symbol: DKFZp434K0435
Not the approved symbol: TRA@
Not the approved symbol: DUB1
Not the approved symbol: SLC35C2
Not the approved symbol: DKFZp686J1895
Not the approved symbol: HSU53209
Not the approved symbol: PRO0132
Not the approved symbol: TXNRD3NB
Not the approved symbol: C1orf127
Not the approved symbol: IRF1-AS1
Not the approved symbol: B-3501
Not the approved symbol: DKFZp547P1613
Not the approved symbol: SFRS4
Not the approved symbol: WDR57
Not the approved symbol: BZRAP1
Not the approved symbol: DKFZp564M2422
Not the approved symbol: EECP
Not the approved symbol: HEL-S-69
Not the approved symbol: RUTBC1
Not the approved symbol: COX4NB
Not the approved symbol: IGL@
Not the approved symbol: Tcr-alpha
Not the approved symbol: RUTBC3
Not the approved symbol: NARG1L
Not the approved symbol: SNC73
Not the approved symbol: NR1C2
Not the approved symbol: SMAP
Not the approved symbol: ORC4L
Not the approved symbol: ELA2B
Not the approved symbol: DKFZp686N224
Not the approved symbol: LOC729862
Not the approved symbol: SIK1B
Not the approved symbol: SLC22A18AS
Not the approved symbol: COX1
Not the approved symbol: HLAC
Not the approved symbol: IQCD
Not the approved symbol: FARSLA
Not the approved symbol: HEL-S-89n
Not the approved symbol: HIST1H2BC
Not the approved symbol: IQCA1L
Not the approved symbol: CXorf1
Not the approved symbol: DKFZp686K03196
Not the approved symbol: PHB
Not the approved symbol: Nbla10236
Not the approved symbol: C17orf85
Not the approved symbol: MST075
Not the approved symbol: FLJ10324
Not the approved symbol: LOC392647
Not the approved symbol: KIAA0415
Not the approved symbol: DKFZp434G0715
Not the approved symbol: IQCA1
Not the approved symbol: C12orf4
Not the approved symbol: DOC-1R
Not the approved symbol: tmp_locus_29
Not the approved symbol: hCG_1996542
Not the approved symbol: SLC66A1L
Not the approved symbol: HEL-S-61
Not the approved symbol: C20orf194
Not the approved symbol: C6orf11
Not the approved symbol: C14orf178
Not the approved symbol: ZNRD1
Not the approved symbol: MGC13033
Not the approved symbol: NR1B3
Not the approved symbol: ENSG00000256500
Not the approved symbol: FAM126A
Not the approved symbol: IKBKAP
Not the approved symbol: ENSG00000248751
Not the approved symbol: KIAA1147
Not the approved symbol: SEPT6
Not the approved symbol: TMEPAI
Not the approved symbol: DKFZp586M1622
Not the approved symbol: ORF
Not the approved symbol: FNBP3
Not the approved symbol: pp9964
Not the approved symbol: HEL-S-273
Not the approved symbol: TRIM39R
Not the approved symbol: PPGB
Not the approved symbol: C1orf57
Not the approved symbol: pk
Not the approved symbol: C2orf73
Not the approved symbol: NADH3
Not the approved symbol: LOC401296
Not the approved symbol: SFRS2
Not the approved symbol: DKFZp686A1668
Not the approved symbol: L1RE1
Not the approved symbol: FLJ00318
Not the approved symbol: C21orf57
Not the approved symbol: QARS
Not the approved symbol: EMS1
Not the approved symbol: PC326
Not the approved symbol: TUSC5
Not the approved symbol: C17orf49
Not the approved symbol: GATD3B
Not the approved symbol: MGC24125
Not the approved symbol: hCG_1657189
Not the approved symbol: DKFZp686O1117
Not the approved symbol: SPC18
Not the approved symbol: PECI
Not the approved symbol: HZF16
Not the approved symbol: STK19
Not the approved symbol: hCG_1818547
Not the approved symbol: PHP14
Not the approved symbol: GC20
Not the approved symbol: C1orf48
Not the approved symbol: HNRPUL1
Not the approved symbol: TUBB2C
Not the approved symbol: cICK0721Q.2
Not the approved symbol: RNPC4
Not the approved symbol: HEL-S-71
Not the approved symbol: MB2
Not the approved symbol: IMUP
Not the approved symbol: SPACIA1
Not the approved symbol: C18orf55
Not the approved symbol: DKFZp686E2459
Not the approved symbol: UBE1
Not the approved symbol: CYR61
Not the approved symbol: EPFP1
Not the approved symbol: FLJ34048
Not the approved symbol: LOC730441
Not the approved symbol: ENSG00000272772
Not the approved symbol: HEL-S-25
Not the approved symbol: MAP3K7IP1
Not the approved symbol: HEL-S-95
Not the approved symbol: KLHDC5
Not the approved symbol: ENSG00000254692
Not the approved symbol: HEL-S-108
Not the approved symbol: DKFZp451L0319
Not the approved symbol: HEL-S-102
Not the approved symbol: C22orf9
Not the approved symbol: DMA
Not the approved symbol: EL52
Not the approved symbol: EFCAB2
Not the approved symbol: DKFZp686A1765
Not the approved symbol: MERP1
Not the approved symbol: LAS2
Not the approved symbol: CK1E
Not the approved symbol: DFNA5
Not the approved symbol: C6orf142
Not the approved symbol: HCTP4
Not the approved symbol: C14orf1
Not the approved symbol: ARD1A
Not the approved symbol: DKFZp686N18198
Not the approved symbol: COX3
Not the approved symbol: TUB4q
Not the approved symbol: DARC
Not the approved symbol: COX2
Not the approved symbol: UGRP1
Not the approved symbol: NHP2L1
Not the approved symbol: ENSG00000275778
Not the approved symbol: pp9457
Not the approved symbol: ENSG00000203546
Not the approved symbol: FGFR2-AHCYL1
Not the approved symbol: zf30
Not the approved symbol: APOBEC3DE
Not the approved symbol: hCG_2044837
Not the approved symbol: MYHbeta
Not the approved symbol: OSTCL
Not the approved symbol: GAS8
Not the approved symbol: KIAA1305
Not the approved symbol: DKFZp686I05169
Not the approved symbol: MST065
Not the approved symbol: HEL-211
Not the approved symbol: ORC5L
Not the approved symbol: KIAA0355
Not the approved symbol: LOR
Not the approved symbol: dik
Not the approved symbol: PSM9
Not the approved symbol: IFP38
Not the approved symbol: KIAA2026
Not the approved symbol: DKFZp686D0880
Not the approved symbol: C8orf30A
Not the approved symbol: DKFZp761G0818
Not the approved symbol: BCR-ABL
Not the approved symbol: DKFZp566C233
Not the approved symbol: ATP5G3
Not the approved symbol: HEL111
Not the approved symbol: FLJ38668
Not the approved symbol: ENSG00000249590
Not the approved symbol: NEPRO
Not the approved symbol: HEL-213
Not the approved symbol: SEPT9
Not the approved symbol: TRA1
Not the approved symbol: HEL32
Not the approved symbol: MLL/AF6
Not the approved symbol: ENSG00000282988
Not the approved symbol: FKSG83
Not the approved symbol: HEL-S-43
Not the approved symbol: DKFZp686I04196
Not the approved symbol: HIST1H2BE
Not the approved symbol: DKFZp781N011
Not the approved symbol: BCR/ABL
Not the approved symbol: PS1TP5BP1
Not the approved symbol: YWHAE/FAM22A
Not the approved symbol: KIAA0864
Not the approved symbol: PDZD3
Not the approved symbol: KIAA1218
Not the approved symbol: DKFZp686A1782
Not the approved symbol: CUSTOS
Not the approved symbol: DKFZp762H177
Not the approved symbol: V1-11
Not the approved symbol: B-raf
Not the approved symbol: MGC4677
Not the approved symbol: DKFZp762B153
Not the approved symbol: C19orf2
Not the approved symbol: ZNFN1A2
Not the approved symbol: NPD011
Not the approved symbol: TRE17
Not the approved symbol: DKFZP586N0721
Not the approved symbol: HEL-S-304
Not the approved symbol: C7orf50
Not the approved symbol: DAZAP1/MEF2D
Not the approved symbol: TSPYL
Not the approved symbol: FLJ13057
Not the approved symbol: LINC01558
Not the approved symbol: IGK@
Not the approved symbol: TNFSF6
Not the approved symbol: H3F3B
Not the approved symbol: SELS
Not the approved symbol: HIST1H1E
Not the approved symbol: IHPK2
Not the approved symbol: EIF3S9
Not the approved symbol: MMTAG2
Not the approved symbol: KCT2
Not the approved symbol: BAP18
Not the approved symbol: ATP6
Not the approved symbol: HEL-S-100n
Not the approved symbol: DKFZp781L0540
Not the approved symbol: DKFZp666O0110
Not the approved symbol: HEL-S-303
Not the approved symbol: HEL-S-271
Not the approved symbol: ATP5J
Not the approved symbol: Par1b
Not the approved symbol: TCEB3B
Not the approved symbol: ACT
Not the approved symbol: DKFZp686J1372
Not the approved symbol: p72syk
Not the approved symbol: PARK2
Not the approved symbol: DKFZp564E242
Not the approved symbol: CENPJ
Not the approved symbol: DKFZp564J0123
Not the approved symbol: DKFZp686E23209
Not the approved symbol: KIAA1683
Not the approved symbol: dystrophin
Not the approved symbol: C2orf83
Not the approved symbol: DKFZp781N1423
Not the approved symbol: FY
Not the approved symbol: HEL-S-69p
Not the approved symbol: GDH
Not the approved symbol: HOXA-9
Not the approved symbol: MYCL1
Not the approved symbol: NR3C4
Not the approved symbol: QK3
Not the approved symbol: NAG13
Not the approved symbol: hCG_23341
Not the approved symbol: DKFZp434D1428
Not the approved symbol: FLJ10842
Not the approved symbol: DKFZP586J0619
Not the approved symbol: TTMP
Not the approved symbol: CDW52
Not the approved symbol: NR2A1
Not the approved symbol: hCG_33128
Not the approved symbol: HIDE1
Not the approved symbol: IGH@
Not the approved symbol: ENSG00000262660
Not the approved symbol: AAG1
Not the approved symbol: CDCrel-1
Not the approved symbol: C21orf66
Not the approved symbol: C4orf3
Not the approved symbol: hfzo2
Not the approved symbol: LOC401309
Not the approved symbol: HIST1H2AH
Not the approved symbol: PNAS-3
Not the approved symbol: HEL-75
Not the approved symbol: FLJ00163
Not the approved symbol: HEL-S-128m
Not the approved symbol: BAT2L
Not the approved symbol: ERAF
Not the approved symbol: BVES
Not the approved symbol: DKFZP564B147
Not the approved symbol: GRP94c
Not the approved symbol: hCG_1723909
Not the approved symbol: ND2
Not the approved symbol: BLR1
Not the approved symbol: HBEBP1
Not the approved symbol: ZFAB
Not the approved symbol: TM4SF2
Not the approved symbol: PCTK1
Not the approved symbol: VH3
Not the approved symbol: ENSG00000260007
Not the approved symbol: XRCC6BP1
Not the approved symbol: GHB3
Not the approved symbol: WDR51B
Not the approved symbol: MHC
Not the approved symbol: TMEM199
Not the approved symbol: SPG20
Not the approved symbol: ENSG00000272162
Not the approved symbol: HEL-S-72
Not the approved symbol: PAAT
Not the approved symbol: ALR
Not the approved symbol: EIF3S3
Not the approved symbol: HLA-B57
Not the approved symbol: hCG_2008078
Not the approved symbol: ND4
Not the approved symbol: MFI
Not the approved symbol: SBBI23
Not the approved symbol: NR1F3
Not the approved symbol: HEL114
Not the approved symbol: TOM7
Not the approved symbol: MGC4836
Not the approved symbol: ZNF323
Not the approved symbol: C1
Not the approved symbol: PRIC295
Not the approved symbol: LEG1
Not the approved symbol: DC-UbP
Not the approved symbol: INADL
Not the approved symbol: GPErik
Not the approved symbol: P5CR2
Not the approved symbol: EURL
Not the approved symbol: SIAT4C
Not the approved symbol: HLA-Cw
Not the approved symbol: SIX6OS1
Not the approved symbol: ANUBL1
Not the approved symbol: DKFZp686L0695
Not the approved symbol: EIF3S2
Not the approved symbol: C18orf21
Not the approved symbol: ST3GalIII
Not the approved symbol: pp10122
Not the approved symbol: PP2135
Not the approved symbol: ERVWE1
Not the approved symbol: DKFZp547I014
Not the approved symbol: PP35
Not the approved symbol: TNRC4
Not the approved symbol: C14orf166
Not the approved symbol: DRIP4
Not the approved symbol: HEL-S-34
Not the approved symbol: NR3A2
Not the approved symbol: DKFZp686A01173
Not the approved symbol: HEL-215
Not the approved symbol: FLJ00305
Not the approved symbol: TFG/ALK
Not the approved symbol: DKFZp686P09201
Not the approved symbol: SFRS5
Not the approved symbol: NY-CO-41
Not the approved symbol: POLE1
Not the approved symbol: HEL164
Not the approved symbol: hCG_2022592
Not the approved symbol: C17orf80
Not the approved symbol: DKFZp686E10210
Not the approved symbol: HEL-S-22
Not the approved symbol: HNRPA1
Not the approved symbol: DKFZp666G145
Not the approved symbol: TU3A
Not the approved symbol: hCG_1994130
Not the approved symbol: HIP2
Not the approved symbol: ENSG00000263620
Not the approved symbol: ARL17
Not the approved symbol: MGC27345
Not the approved symbol: HEL-S-277
Not the approved symbol: KIAA1569
Not the approved symbol: hCG_1984214
Not the approved symbol: RNP24
Not the approved symbol: DKFZp686B20267
Not the approved symbol: ENSG00000258653
Not the approved symbol: HEL2
Not the approved symbol: FLJ00246
Not the approved symbol: FBXO18
Not the approved symbol: LOC642947
Not the approved symbol: EDG2
Not the approved symbol: DKFZp686N02209
Not the approved symbol: UNQ1916
Not the approved symbol: CCDC96
Not the approved symbol: C2orf50
Not the approved symbol: PML-RAR

       Input Approved symbol
0  LOC554223             NaN
1      TRGV8           TRGV8
2      CEFIP        C10orf71
3  LINC01565       LINC01565
4       MUXA             NaN

Number of interactions: 759122

,Uniprot_A,Uniprot_B,PPI_pair,Gene_approved_A,Gene_approved_B,gene_pair
0,A0A024R0H7,Q8TB24,A0A024R0H7:Q8TB24,WDR77,RIN3,RIN3:WDR77
1,A0A024R0L6,Q5S007,A0A024R0L6:Q5S007,PAFAH1B3,LRRK2,LRRK2:PAFAH1B3
2,A0A024R1A3,Q5S007,A0A024R1A3:Q5S007,UBA1,LRRK2,LRRK2:UBA1
3,A0A024R2I8,O15379,A0A024R2I8:O15379,THRB,HDAC3,HDAC3:THRB
4,A0A024R2I8,O75376,A0A024R2I8:O75376,THRB,NCOR1,NCOR1:THRB

In [ ]:
## Merge and process BioPlex lists

# concatenate interactomes (downloaded from BioPlex)
bioplex_file_list = ["BioPlex_293T_Network_10K_Dec_2019.tsv", "BioPlex_HCT116_Network_5.5K_Dec_2019.tsv", "BioPlex_interactionList_v2.tsv", "BioPlex_interactionList_v4a.tsv"]
bioplex_interactomes = []
for bioplex_file in bioplex_file_list:
    bioplex_file_path = os.path.join(root_dir, "_DATA/_COMMON/network/BioPlex/", bioplex_file)
    interactome = pd.read_table(bioplex_file_path)
    interactome.columns = [x.replace(" ", "") for x in interactome.columns]
    interactome["gene_pair"] = interactome.apply(lambda row: ":".join(sorted([row["SymbolA"], row["SymbolB"]])), axis=1)
    interactome = interactome.drop_duplicates(subset=["gene_pair"])
    interactome = interactome[["UniprotA", "UniprotB", "SymbolA", "SymbolB", "gene_pair"]]
    # display(interactome.head())
    bioplex_interactomes.append(interactome)
bioplex_all_interactome = pd.concat(bioplex_interactomes, axis=0).drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)

# !! Issue: but many original gene names in BioPlex are not the approved HGNC symbols, need to map them to the approved symbols

# # generate the gene lis for those genes that are not approved HGNC symbols
# hgnc_gene_info = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/genes/HGNC_proteincoding.txt"))
# bioplex_all_interactome_genes = pd.DataFrame(list(set(list(bioplex_all_interactome["SymbolA"].unique()) + list(bioplex_all_interactome["SymbolB"].unique()))))
# bioplex_all_interactome_genes[~bioplex_all_interactome_genes[0].isin(list(hgnc_gene_info["symbol"]))].to_csv(os.path.join(root_dir, "_DATA/_COMMON/network/BioPlex/BioPlex_all_genes_notapproved.txt"), sep='\t', index=None, header=None)

# load the appoved HGNC mapping only for those genes that are not approved symbols
bioplex_all_notapproved_genes_hgnc = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/BioPlex/BioPlex_all_genes_notapproved_hgnc.csv"), sep=',')
genes_approved = []
for input_gene in bioplex_all_notapproved_genes_hgnc["Input"].unique():
    hgnc_inputgene = bioplex_all_notapproved_genes_hgnc[bioplex_all_notapproved_genes_hgnc["Input"] == input_gene]
    hgnc_inputgene_appr = hgnc_inputgene[hgnc_inputgene["Match type"] == "Approved symbol"]
    if len(hgnc_inputgene_appr) == 0: # for input genes that are not approved HGNC symbols, replace with all the mapped approved symbols
        print("Not the approved symbol:", input_gene)
        # display(hgnc_inputgene)
        genes_approved.append(hgnc_inputgene[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) == 1: # for input genes that are approved HGNC symbols
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) > 1: # for input genes that are approved HGNC symbols
        # display(genes_hgnc_inputgene_apr)
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
genes_approved = pd.concat(genes_approved, axis=0).reset_index(drop=True)
display(genes_approved.head())

# finally, using the clean, filled and mostly approved symbols as gene names to generate gene_pairs and filter out duplicated ones
bioplex_all_interactome = pd.merge(bioplex_all_interactome, genes_approved, left_on="SymbolA", right_on="Input", how="left").rename(columns={"Approved symbol":"SymbolA_approved"}).drop(columns=["Input"])
bioplex_all_interactome["SymbolA_approved"] = bioplex_all_interactome.apply(lambda row: row["SymbolA_approved"] if pd.isna(row["SymbolA_approved"]) == False else row["SymbolA"], axis=1) # if no approved symbol, just use the original one
bioplex_all_interactome = pd.merge(bioplex_all_interactome, genes_approved, left_on="SymbolB", right_on="Input", how="left").rename(columns={"Approved symbol":"SymbolB_approved"}).drop(columns=["Input"])
bioplex_all_interactome["SymbolB_approved"] = bioplex_all_interactome.apply(lambda row: row["SymbolB_approved"] if pd.isna(row["SymbolB_approved"]) == False else row["SymbolB"], axis=1) # if no approved symbol, just use the original one
bioplex_all_interactome["gene_pair"] = bioplex_all_interactome.apply(lambda row: ":".join(sorted([row["SymbolA_approved"], row["SymbolB_approved"]])), axis=1)
bioplex_all_interactome = bioplex_all_interactome.drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)
bioplex_all_interactome = bioplex_all_interactome[["UniprotA", "UniprotB", "SymbolA_approved", "SymbolB_approved", "gene_pair"]]

# save the merged interactome with filled gene names and approved symbols, and the gene pairs with approved symbols
bioplex_all_interactome_file = os.path.join(root_dir, "_DATA/_COMMON/network/BioPlex/BioPlex_all.tsv")
bioplex_all_interactome.to_csv(bioplex_all_interactome_file, sep='\t', index=None)
print("Number of interactions:", len(bioplex_all_interactome))
bioplex_all_interactome.head()

Not the approved symbol: LOC554223
Not the approved symbol: NBPF24
Not the approved symbol: LOC100507685
Not the approved symbol: KIAA1161
Not the approved symbol: C19orf20
Not the approved symbol: RAB7L1
Not the approved symbol: C1orf212
Not the approved symbol: C20orf106
Not the approved symbol: PET112L
Not the approved symbol: FAM122C
Not the approved symbol: CXorf23
Not the approved symbol: GRINL1A
Not the approved symbol: C5orf35
Not the approved symbol: H2AFB1
Not the approved symbol: MYST1
Not the approved symbol: KIAA0748
Not the approved symbol: GATSL3
Not the approved symbol: RAD51L1
Not the approved symbol: C10orf84
Not the approved symbol: YARS
Not the approved symbol: C9orf139
Not the approved symbol: KIAA1009
Not the approved symbol: ARSE
Not the approved symbol: STRA13
Not the approved symbol: C1orf38
Not the approved symbol: FAM18A
Not the approved symbol: FAM166B
Not the approved symbol: C11orf10
Not the approved symbol: COPG
Not the approved symbol: FAM45A
Not the approved symbol: TMEM2
Not the approved symbol: GOLGA8C
Not the approved symbol: C2orf54
Not the approved symbol: C11orf51
Not the approved symbol: SC5DL
Not the approved symbol: C1orf65
Not the approved symbol: MRPS36
Not the approved symbol: FAM96A
Not the approved symbol: FAM48A
Not the approved symbol: SEPT3
Not the approved symbol: C8orf22
Not the approved symbol: C20orf7
Not the approved symbol: C12orf10
Not the approved symbol: SPINLW1
Not the approved symbol: KIAA1731
Not the approved symbol: C5orf64
Not the approved symbol: MTL5
Not the approved symbol: WHSC2
Not the approved symbol: C9orf82
Not the approved symbol: C9orf150
Not the approved symbol: TTC15
Not the approved symbol: ACCN5
Not the approved symbol: CECR5
Not the approved symbol: SKIV2L2
Not the approved symbol: HIST1H4L
Not the approved symbol: KIAA1468
Not the approved symbol: CCDC113
Not the approved symbol: C9orf96
Not the approved symbol: CBWD2
Not the approved symbol: BOD1P
Not the approved symbol: C12orf45
Not the approved symbol: PPP2R4
Not the approved symbol: AZI1
Not the approved symbol: FAM100B
Not the approved symbol: MKI67IP
Not the approved symbol: C2orf48
Not the approved symbol: FAM36A
Not the approved symbol: MESDC2
Not the approved symbol: SUV420H1
Not the approved symbol: WIBG
Not the approved symbol: OCLM
Not the approved symbol: FAM122A
Not the approved symbol: FAM19A1
Not the approved symbol: CCBL2
Not the approved symbol: WAPAL
Not the approved symbol: HIST1H2AB
Not the approved symbol: C1orf64
Not the approved symbol: CBWD7
Not the approved symbol: C5orf44
Not the approved symbol: C15orf26
Not the approved symbol: C7orf60
Not the approved symbol: DARS
Not the approved symbol: C19orf70
Not the approved symbol: LOC441493
Not the approved symbol: C16orf79
Not the approved symbol: ATP5B
Not the approved symbol: EIF2C2
Not the approved symbol: BRP44L
Not the approved symbol: C7orf42
Not the approved symbol: C6orf81
Not the approved symbol: C1orf112
Not the approved symbol: KIAA0368
Not the approved symbol: C20orf3
Not the approved symbol: GBA
Not the approved symbol: C12orf53
Not the approved symbol: HIST1H2BK
Not the approved symbol: C15orf54
Not the approved symbol: C7orf53
Not the approved symbol: H2AFX
Not the approved symbol: C9orf156
Not the approved symbol: C9orf125
Not the approved symbol: EPRS
Not the approved symbol: PHF15
Not the approved symbol: KIAA0226
Not the approved symbol: CXorf26
Not the approved symbol: C17orf104
Not the approved symbol: TMEM111
Not the approved symbol: C15orf17
Not the approved symbol: LOC254896
Not the approved symbol: IL1F6
Not the approved symbol: CENPC1
Not the approved symbol: WDR67
Not the approved symbol: GLTSCR1
Not the approved symbol: MARS
Not the approved symbol: TCEB2
Not the approved symbol: C1orf9
Not the approved symbol: TMCO7
Not the approved symbol: HIST1H4G
Not the approved symbol: RTCD1
Not the approved symbol: C8orf84
Not the approved symbol: FAM54B
Not the approved symbol: USMG5
Not the approved symbol: SARS
Not the approved symbol: OSTalpha
Not the approved symbol: C21orf70
Not the approved symbol: RNF216L
Not the approved symbol: HRASLS
Not the approved symbol: FAM115A
Not the approved symbol: DUX2
Not the approved symbol: C21orf56
Not the approved symbol: C16orf75
Not the approved symbol: C11orf83
Not the approved symbol: KIAA0284
Not the approved symbol: C16orf48
Not the approved symbol: C4orf49
Not the approved symbol: FAM54A
Not the approved symbol: C7orf69
Not the approved symbol: BHLHB9
Not the approved symbol: SEPT7
Not the approved symbol: C7orf26
Not the approved symbol: C3orf58
Not the approved symbol: GPR110
Not the approved symbol: HIST1H3F
Not the approved symbol: H2BFWT
Not the approved symbol: SDCCAG3
Not the approved symbol: ANP32C
Not the approved symbol: C5orf28
Not the approved symbol: C11orf84
Not the approved symbol: C16orf80
Not the approved symbol: HIST1H2BL
Not the approved symbol: TMEM57
Not the approved symbol: ATP5G2
Not the approved symbol: C12orf49
Not the approved symbol: MLL5
Not the approved symbol: KAL1
Not the approved symbol: KIAA0895
Not the approved symbol: C10orf107
Not the approved symbol: C17orf37
Not the approved symbol: MYST3
Not the approved symbol: RTDR1
Not the approved symbol: CASC5
Not the approved symbol: PHF16
Not the approved symbol: C2orf65
Not the approved symbol: KIAA0564
Not the approved symbol: C16orf93
Not the approved symbol: C5orf41
Not the approved symbol: HIST1H2AG
Not the approved symbol: FAM116B
Not the approved symbol: MRVI1
Not the approved symbol: FKSG43
Not the approved symbol: C14orf21
Not the approved symbol: MARCH2
Not the approved symbol: MEIR5
Not the approved symbol: LOC100287045
Not the approved symbol: PPAP2A
Not the approved symbol: HIN1L
Not the approved symbol: C8orf59
Not the approved symbol: TCP10
Not the approved symbol: KIAA1984
Not the approved symbol: ACCN4
Not the approved symbol: FAM178A
Not the approved symbol: KIAA1712
Not the approved symbol: GRRP1
Not the approved symbol: THEG
Not the approved symbol: GPR125
Not the approved symbol: C3orf26
Not the approved symbol: C19orf68
Not the approved symbol: C17orf28
Not the approved symbol: HIST1H3B
Not the approved symbol: C9orf41
Not the approved symbol: CLLU1OS
Not the approved symbol: EIF2C3
Not the approved symbol: C3orf64
Not the approved symbol: AKD1
Not the approved symbol: FAM70B
Not the approved symbol: C15orf63
Not the approved symbol: FAM60A
Not the approved symbol: SEPT8
Not the approved symbol: ND1
Not the approved symbol: MLL
Not the approved symbol: SLC22A18
Not the approved symbol: CXorf59
Not the approved symbol: CBARA1
Not the approved symbol: C19orf39
Not the approved symbol: C4orf52
Not the approved symbol: MUTED
Not the approved symbol: C1orf131
Not the approved symbol: C18orf10
Not the approved symbol: C6orf162
Not the approved symbol: WASH1
Not the approved symbol: KIAA1804
Not the approved symbol: C1orf49
Not the approved symbol: CCDC55
Not the approved symbol: EFHA1
Not the approved symbol: EMID2
Not the approved symbol: CCDC65
Not the approved symbol: KIAA0182
Not the approved symbol: C20orf111
Not the approved symbol: C5orf32
Not the approved symbol: ICT1
Not the approved symbol: C16orf88
Not the approved symbol: FAM127A
Not the approved symbol: HARS
Not the approved symbol: LOC100507680
Not the approved symbol: C14orf166B
Not the approved symbol: WHSC1
Not the approved symbol: RG9MTD2
Not the approved symbol: C6orf195
Not the approved symbol: MFSD4
Not the approved symbol: MUM1
Not the approved symbol: CIR1
Not the approved symbol: KIAA1919
Not the approved symbol: C14orf101
Not the approved symbol: CYTB
Not the approved symbol: ALS2CR4
Not the approved symbol: C19orf29
Not the approved symbol: C4orf37
Not the approved symbol: C15orf38
Not the approved symbol: WBP5
Not the approved symbol: C19orf50
Not the approved symbol: FAM160B2
Not the approved symbol: C3orf1
Not the approved symbol: C17orf57
Not the approved symbol: PALM2-AKAP2
Not the approved symbol: C7orf59
Not the approved symbol: EFCAB1
Not the approved symbol: LOC613266
Not the approved symbol: KIAA1539
Not the approved symbol: C9orf119
Not the approved symbol: KIAA1467
Not the approved symbol: APITD1
Not the approved symbol: C4orf22
Not the approved symbol: B3GNT1
Not the approved symbol: C8orf80
Not the approved symbol: HIST1H3H
Not the approved symbol: C3orf43
Not the approved symbol: ODZ3
Not the approved symbol: C14orf118
Not the approved symbol: ZNF767
Not the approved symbol: C14orf2
Not the approved symbol: C9orf64
Not the approved symbol: C14orf80
Not the approved symbol: HRASLS2
Not the approved symbol: HNRPDL
Not the approved symbol: LOC729991
Not the approved symbol: AIM1L
Not the approved symbol: KIAA1543
Not the approved symbol: C14orf37
Not the approved symbol: C6orf168
Not the approved symbol: AGPHD1
Not the approved symbol: C6orf203
Not the approved symbol: SMEK1
Not the approved symbol: RUNDC2A
Not the approved symbol: SLMO2
Not the approved symbol: ST5
Not the approved symbol: C17orf60
Not the approved symbol: C9orf100
Not the approved symbol: LRRC33
Not the approved symbol: MLL2
Not the approved symbol: C4orf19
Not the approved symbol: LPPR4
Not the approved symbol: SEP15
Not the approved symbol: C11orf30
Not the approved symbol: C20orf72
Not the approved symbol: C2orf53
Not the approved symbol: TTC30B
Not the approved symbol: GPR126
Not the approved symbol: FUK
Not the approved symbol: H2AFB3
Not the approved symbol: CCDC103
Not the approved symbol: FAM26E
Not the approved symbol: C17orf109
Not the approved symbol: C10orf93
Not the approved symbol: FAM59A
Not the approved symbol: XAGE1D
Not the approved symbol: C6orf204
Not the approved symbol: C18orf19
Not the approved symbol: CCDC109B
Not the approved symbol: C3orf10
Not the approved symbol: C20orf12
Not the approved symbol: NDNL2
Not the approved symbol: PRPF4B
Not the approved symbol: ZUFSP
Not the approved symbol: CARD17
Not the approved symbol: FAM84B
Not the approved symbol: C7orf44
Not the approved symbol: FAM69B
Not the approved symbol: PAPD7
Not the approved symbol: C12orf34
Not the approved symbol: KIAA1109
Not the approved symbol: AGPAT9
Not the approved symbol: C20orf24
Not the approved symbol: PTPLA
Not the approved symbol: FAM127B
Not the approved symbol: PNMA6C
Not the approved symbol: C19orf6
Not the approved symbol: C3orf39
Not the approved symbol: CCDC123
Not the approved symbol: TROVE2
Not the approved symbol: C10orf81
Not the approved symbol: C4orf39
Not the approved symbol: GBAS
Not the approved symbol: MLL4
Not the approved symbol: C7orf11
Not the approved symbol: MLL3
Not the approved symbol: CCDC67
Not the approved symbol: PAPD5
Not the approved symbol: C16orf61
Not the approved symbol: ZNF828
Not the approved symbol: C2orf44
Not the approved symbol: C11orf49
Not the approved symbol: NARFL
Not the approved symbol: MB21D1
Not the approved symbol: GK3P
Not the approved symbol: FAM113A
Not the approved symbol: H1FNT
Not the approved symbol: PRIC285
Not the approved symbol: CTGF
Not the approved symbol: ATP5C1
Not the approved symbol: C15orf57
Not the approved symbol: TARSL2
Not the approved symbol: GPR182
Not the approved symbol: DDX12
Not the approved symbol: C18orf8
Not the approved symbol: ZNF192
Not the approved symbol: PROSC
Not the approved symbol: SEPT11
Not the approved symbol: C16orf53
Not the approved symbol: C12orf66
Not the approved symbol: SEPT5
Not the approved symbol: TSSC1
Not the approved symbol: SLMO1
Not the approved symbol: EIF2C4
Not the approved symbol: MYLPF
Not the approved symbol: LOC338797
Not the approved symbol: METTL21D
Not the approved symbol: MKL1
Not the approved symbol: C9orf140
Not the approved symbol: PAPL
Not the approved symbol: MOBKL3
Not the approved symbol: ATP5F1
Not the approved symbol: SMEK2
Not the approved symbol: CSRP2BP
Not the approved symbol: C12orf69
Not the approved symbol: PLA2G16
Not the approved symbol: MLLT4
Not the approved symbol: LRRC16A
Not the approved symbol: PROL1
Not the approved symbol: TMEM85
Not the approved symbol: FAM103A1
Not the approved symbol: ACCN1
Not the approved symbol: C19orf46
Not the approved symbol: C19orf28
Not the approved symbol: MFI2
Not the approved symbol: C16orf62
Not the approved symbol: KIAA1033
Not the approved symbol: MARCH7
Not the approved symbol: FAM46A
Not the approved symbol: MTERFD2
Not the approved symbol: SEPT10
Not the approved symbol: KIAA0247
Not the approved symbol: C17orf89
Not the approved symbol: C14orf149
Not the approved symbol: H2AFZ
Not the approved symbol: DUS2L
Not the approved symbol: MARCH6
Not the approved symbol: OSTBETA
Not the approved symbol: HBXIP
Not the approved symbol: C12orf73
Not the approved symbol: TMEM194A
Not the approved symbol: C15orf58
Not the approved symbol: MARCH9
Not the approved symbol: C15orf27
Not the approved symbol: KIAA0922
Not the approved symbol: C19orf63
Not the approved symbol: LRRC48
Not the approved symbol: NOTCH2NL
Not the approved symbol: FAM129B
Not the approved symbol: C14orf104
Not the approved symbol: C9orf116
Not the approved symbol: FLJ36031
Not the approved symbol: C8orf73
Not the approved symbol: FAM164C
Not the approved symbol: C13orf29
Not the approved symbol: ATP5I
Not the approved symbol: MESDC1
Not the approved symbol: C14orf148
Not the approved symbol: TTC35
Not the approved symbol: C2orf7
Not the approved symbol: WDYHV1
Not the approved symbol: C15orf29
Not the approved symbol: METTL10
Not the approved symbol: MUT
Not the approved symbol: C19orf51
Not the approved symbol: ANKRD43
Not the approved symbol: IL1F8
Not the approved symbol: GATS
Not the approved symbol: C3orf45
Not the approved symbol: C12orf23
Not the approved symbol: ATP5H
Not the approved symbol: FTSJD1
Not the approved symbol: ND6
Not the approved symbol: DYX1C1
Not the approved symbol: PCNX
Not the approved symbol: C17orf103
Not the approved symbol: FAM160B1
Not the approved symbol: C17orf106
Not the approved symbol: PYCRL
Not the approved symbol: FAM127C
Not the approved symbol: PVRL2
Not the approved symbol: LOC100294276
Not the approved symbol: FAM40B
Not the approved symbol: C12orf24
Not the approved symbol: SRPR
Not the approved symbol: C3orf31
Not the approved symbol: C20orf29
Not the approved symbol: LASS4
Not the approved symbol: C17orf59
Not the approved symbol: C7orf30
Not the approved symbol: C9orf91
Not the approved symbol: C20orf20
Not the approved symbol: C7orf55
Not the approved symbol: KIAA1704
Not the approved symbol: SQRDL
Not the approved symbol: MSL3P1
Not the approved symbol: GPR98
Not the approved symbol: HN1
Not the approved symbol: FAM150B
Not the approved symbol: C10orf137
Not the approved symbol: EFCAB4A
Not the approved symbol: LPPR1
Not the approved symbol: CCDC111
Not the approved symbol: C1orf106
Not the approved symbol: LOC100510589
Not the approved symbol: C6orf226
Not the approved symbol: OBFC2B
Not the approved symbol: REXO1L1
Not the approved symbol: SLC9A3R1
Not the approved symbol: COBRA1
Not the approved symbol: C11orf1
Not the approved symbol: GRAMD2
Not the approved symbol: C1orf88
Not the approved symbol: C11orf31
Not the approved symbol: H2AFY2
Not the approved symbol: C1orf103
Not the approved symbol: CARS
Not the approved symbol: HDHD1
Not the approved symbol: TMEM90B
Not the approved symbol: C7orf10
Not the approved symbol: C9orf171
Not the approved symbol: WISP3
Not the approved symbol: SELO
Not the approved symbol: C10orf58
Not the approved symbol: LOC100509457
Not the approved symbol: HIST1H4F
Not the approved symbol: SSFA2
Not the approved symbol: RQCD1
Not the approved symbol: TMEM8A
Not the approved symbol: HIST1H3J
Not the approved symbol: FAM175A
Not the approved symbol: ROD1
Not the approved symbol: C10orf2
Not the approved symbol: C12orf26
Not the approved symbol: FAM176B
Not the approved symbol: MST4
Not the approved symbol: GNB2L1
Not the approved symbol: C3orf21
Not the approved symbol: C10orf18
Not the approved symbol: C5orf45
Not the approved symbol: FAM105B
Not the approved symbol: C1orf168
Not the approved symbol: MLF1IP
Not the approved symbol: C12orf41
Not the approved symbol: TEPP
Not the approved symbol: KIAA1244
Not the approved symbol: CTAGEP
Not the approved symbol: C2orf27A
Not the approved symbol: TMEM173
Not the approved symbol: B3GALTL
Not the approved symbol: C3orf19
Not the approved symbol: C2orf56
Not the approved symbol: FAM113B
Not the approved symbol: PLDN
Not the approved symbol: C16orf13
Not the approved symbol: LOC388882
Not the approved symbol: C7orf23
Not the approved symbol: ARNTL
Not the approved symbol: KIAA1841
Not the approved symbol: HIST1H2AE
Not the approved symbol: IL28B
Not the approved symbol: MTERFD3
Not the approved symbol: C14orf105
Not the approved symbol: C1orf27
Not the approved symbol: ANKRD20A4
Not the approved symbol: HIST1H2BD
Not the approved symbol: SC4MOL
Not the approved symbol: KIAA1826
Not the approved symbol: KIAA1274
Not the approved symbol: FAM86C
Not the approved symbol: C9orf128
Not the approved symbol: SELM
Not the approved symbol: C10orf47
Not the approved symbol: KIAA0100
Not the approved symbol: GLT25D2
Not the approved symbol: FAM116A
Not the approved symbol: DSCR3
Not the approved symbol: KIAA1486
Not the approved symbol: C3orf24
Not the approved symbol: GPR113
Not the approved symbol: HSPC159
Not the approved symbol: GBAP1
Not the approved symbol: JMJD5
Not the approved symbol: TXNRD3NB
Not the approved symbol: GATSL2
Not the approved symbol: FKBP9L
Not the approved symbol: CCDC144B
Not the approved symbol: CP110
Not the approved symbol: C1orf127
Not the approved symbol: TMSL3
Not the approved symbol: DOM3Z
Not the approved symbol: WRB
Not the approved symbol: HIST1H2BA
Not the approved symbol: C1orf150
Not the approved symbol: KIAA1462
Not the approved symbol: FAM5C
Not the approved symbol: C20orf177
Not the approved symbol: C3orf46
Not the approved symbol: ZNF643
Not the approved symbol: FCGR1C
Not the approved symbol: BZRAP1
Not the approved symbol: C17orf42
Not the approved symbol: PHF17
Not the approved symbol: HIST1H4B
Not the approved symbol: C19orf60
Not the approved symbol: LPHN3
Not the approved symbol: TARS
Not the approved symbol: C9orf4
Not the approved symbol: COX4NB
Not the approved symbol: FAM169B
Not the approved symbol: PRSS46
Not the approved symbol: ANKRD56
Not the approved symbol: DDX26B
Not the approved symbol: FAM125A
Not the approved symbol: KIAA0754
Not the approved symbol: C19orf59
Not the approved symbol: ANKRD20A2
Not the approved symbol: HIST1H3I
Not the approved symbol: DEFB109
Not the approved symbol: TTDN1
Not the approved symbol: C9orf173
Not the approved symbol: FAM189A2
Not the approved symbol: MYST4
Not the approved symbol: VIPAR
Not the approved symbol: C9orf23
Not the approved symbol: CCDC84
Not the approved symbol: C9orf89
Not the approved symbol: KIAA1279
Not the approved symbol: C10orf96
Not the approved symbol: ANKRD57
Not the approved symbol: TMEM136
Not the approved symbol: CARKD
Not the approved symbol: TMEM159
Not the approved symbol: CYHR1
Not the approved symbol: C15orf24
Not the approved symbol: CTSL2
Not the approved symbol: ND3
Not the approved symbol: C7orf31
Not the approved symbol: C2orf62
Not the approved symbol: C17orf101
Not the approved symbol: CTAGE6P
Not the approved symbol: BRE
Not the approved symbol: DHFRL1
Not the approved symbol: SEPT12
Not the approved symbol: RG9MTD1
Not the approved symbol: CCDC46
Not the approved symbol: FAM160A1
Not the approved symbol: KBTBD10
Not the approved symbol: C6orf174
Not the approved symbol: SEPN1
Not the approved symbol: TMEM56
Not the approved symbol: C6orf129
Not the approved symbol: FAM172A
Not the approved symbol: ARMC4
Not the approved symbol: ERO1LB
Not the approved symbol: C20orf108
Not the approved symbol: C2orf29
Not the approved symbol: FAM134C
Not the approved symbol: C4orf26
Not the approved symbol: WDR34
Not the approved symbol: TUBB4
Not the approved symbol: LOC100509631
Not the approved symbol: PDDC1

          Input Approved symbol
0     LOC554223             NaN
1        NBPF24          NBPF11
2  LOC100507685             NaN
3      KIAA1161           MYORG
4      C19orf20           TPGS1

Number of interactions: 183022

   UniprotA  UniprotB SymbolA_approved SymbolB_approved    gene_pair
0    P00813    A5A3E0              ADA            POTEF    ADA:POTEF
1  Q8N7W2-2    P26373            BEND7            RPL13  BEND7:RPL13
2  Q8N7W2-2  Q09028-3            BEND7            RBBP4  BEND7:RBBP4
3  Q8N7W2-2    Q9Y3U8            BEND7            RPL36  BEND7:RPL36
4  Q8N7W2-2    P36578            BEND7             RPL4   BEND7:RPL4

In [ ]:
## Merge and process OpenCell interactome

opencell_interactome_file = os.path.join(root_dir, "_DATA/_COMMON/network/OpenCell/opencell-protein-interactions.csv")
opencell_interactome = pd.read_table(opencell_interactome_file, sep=',')
opencell_interactome["interactor_gene_name"] = opencell_interactome["interactor_gene_name"].apply(lambda x: x.split(";"))
opencell_interactome = opencell_interactome.explode("interactor_gene_name")
opencell_interactome = opencell_interactome[["target_gene_name", "interactor_gene_name"]].reset_index(drop=True)
opencell_interactome["gene_pair"] = opencell_interactome.progress_apply(lambda row: ":".join(sorted([row["target_gene_name"], row["interactor_gene_name"]])), axis=1)
opencell_interactome = opencell_interactome.drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)

# !! Issue: but many original gene names in OpenCell are not the approved HGNC symbols, need to map them to the approved symbols

# # generate the gene lis for those genes that are not approved HGNC symbols
# hgnc_gene_info = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/genes/HGNC_proteincoding.txt"))
# opencell_interactome_genes = pd.DataFrame(list(set(list(opencell_interactome["target_gene_name"].unique()) + list(opencell_interactome["interactor_gene_name"].unique()))))
# opencell_interactome_genes[~opencell_interactome_genes[0].isin(list(hgnc_gene_info["symbol"]))].to_csv(os.path.join(root_dir, "_DATA/_COMMON/network/OpenCell/opencell_all_genes_notapproved.txt"), sep='\t', index=None, header=None)

# load the appoved HGNC mapping only for those genes that are not approved symbols
opencell_interactome_genes_hgnc = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/OpenCell/opencell_all_genes_notapproved_hgnc.csv"), sep=',')
genes_approved = []
for input_gene in opencell_interactome_genes_hgnc["Input"].unique():
    hgnc_inputgene = opencell_interactome_genes_hgnc[opencell_interactome_genes_hgnc["Input"] == input_gene]
    hgnc_inputgene_appr = hgnc_inputgene[hgnc_inputgene["Match type"] == "Approved symbol"]
    if len(hgnc_inputgene_appr) == 0: # for input genes that are not approved HGNC symbols, replace with all the mapped approved symbols
        print("Not the approved symbol:", input_gene)
        # display(hgnc_inputgene)
        genes_approved.append(hgnc_inputgene[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) == 1:
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
    elif len(hgnc_inputgene_appr) > 1:
        # display(genes_hgnc_inputgene_apr)
        genes_approved.append(hgnc_inputgene_appr[["Input", "Approved symbol"]])
genes_approved = pd.concat(genes_approved, axis=0).reset_index(drop=True)
display(genes_approved.head())

# finally, using the clean, filled and mostly approved symbols as gene names to generate gene_pairs and filter out duplicated ones
opencell_interactome = pd.merge(opencell_interactome, genes_approved, left_on="target_gene_name", right_on="Input", how="left").rename(columns={"Approved symbol":"target_gene_name_approved"}).drop(columns=["Input"])
opencell_interactome["target_gene_name_approved"] = opencell_interactome.apply(lambda row: row["target_gene_name_approved"] if pd.isna(row["target_gene_name_approved"]) == False else row["target_gene_name"], axis=1) # if no approved symbol, just use the original one
opencell_interactome = pd.merge(opencell_interactome, genes_approved, left_on="interactor_gene_name", right_on="Input", how="left").rename(columns={"Approved symbol":"interactor_gene_name_approved"}).drop(columns=["Input"])
opencell_interactome["interactor_gene_name_approved"] = opencell_interactome.apply(lambda row: row["interactor_gene_name_approved"] if pd.isna(row["interactor_gene_name_approved"]) == False else row["interactor_gene_name"], axis=1) # if no approved symbol, just use the original one
opencell_interactome["gene_pair"] = opencell_interactome.apply(lambda row: ":".join(sorted([row["target_gene_name_approved"], row["interactor_gene_name_approved"]])), axis=1)
opencell_interactome = opencell_interactome.drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)
opencell_interactome = opencell_interactome[["target_gene_name_approved", "interactor_gene_name_approved", "gene_pair"]]

# save the merged interactome with filled gene names and approved symbols, and the gene pairs with approved symbols
opencell_all_interactome_file = os.path.join(root_dir, "_DATA/_COMMON/network/OpenCell/opencell_all.csv")
opencell_interactome.to_csv(opencell_all_interactome_file, sep=",", index=None)
print("Number of interactions:", len(opencell_interactome))
opencell_interactome.head()

100%|██████████| 31838/31838 [00:00<00:00, 189798.79it/s]

Not the approved symbol: FLJ00186
Not the approved symbol: DKFZP434D199
Not the approved symbol: SEPTININININ3
Not the approved symbol: FAM45A
Not the approved symbol: TMEM2
Not the approved symbol: BAT3
Not the approved symbol: SEPTININININ5
Not the approved symbol: MRPS36
Not the approved symbol: TOMM20A
Not the approved symbol: KIAA1211L
Not the approved symbol: BCAR2
Not the approved symbol: C17ORF70
Not the approved symbol: CDC2
Not the approved symbol: SKIV2L2
Not the approved symbol: KIAA1468
Not the approved symbol: NPEPPSL1
Not the approved symbol: HIST2H2AA3
Not the approved symbol: TDP43
Not the approved symbol: C3ORF58
Not the approved symbol: WIBG
Not the approved symbol: WAPAL
Not the approved symbol: HIST1H2AB
Not the approved symbol: C7ORF50
Not the approved symbol: DARS
Not the approved symbol: ATP5B
Not the approved symbol: KIAA0368
Not the approved symbol: GBA
Not the approved symbol: HIST1H2BK
Not the approved symbol: MLK4
Not the approved symbol: C7ORF26
Not the approved symbol: H2AFX
Not the approved symbol: EPRS
Not the approved symbol: YAE1D1
Not the approved symbol: KIAA0226
Not the approved symbol: PEO1
Not the approved symbol: GLTSCR1
Not the approved symbol: MARS
Not the approved symbol: TCEB2
Not the approved symbol: SARS
Not the approved symbol: KIAA0226L
Not the approved symbol: C16ORF62
Not the approved symbol: SEPTININININ9
Not the approved symbol: SDCCAG3
Not the approved symbol: HIST1H2AC
Not the approved symbol: HIST1H2BL
Not the approved symbol: TMEM57
Not the approved symbol: C6ORF106
Not the approved symbol: CXORF57
Not the approved symbol: C12ORF45
Not the approved symbol: MYST3
Not the approved symbol: CASC5
Not the approved symbol: KIF1BBETA
Not the approved symbol: DKFZP434B156
Not the approved symbol: SEPTININININ11
Not the approved symbol: HIST1H2AG
Not the approved symbol: VIMP
Not the approved symbol: DKFZP779C2259
Not the approved symbol: FAM60A
Not the approved symbol: WASH1
Not the approved symbol: HIST1H2AA
Not the approved symbol: CCDC55
Not the approved symbol: WHSC1
Not the approved symbol: PALM2-AKAP2
Not the approved symbol: KIAA1467
Not the approved symbol: HCG_1984214
Not the approved symbol: SMEK1
Not the approved symbol: ST5
Not the approved symbol: TTC30B
Not the approved symbol: PRPF4B
Not the approved symbol: DKFZP686H13261
Not the approved symbol: TOMM70A
Not the approved symbol: NIF3L1BP1
Not the approved symbol: TROVE2
Not the approved symbol: GK3P
Not the approved symbol: CSNK2B-LY6G5B-1181
Not the approved symbol: ATP5C1
Not the approved symbol: C14ORF166
Not the approved symbol: C17ORF49
Not the approved symbol: MKL1
Not the approved symbol: CSRP2BP
Not the approved symbol: MLLT4
Not the approved symbol: LRRC16A
Not the approved symbol: FAM103A1
Not the approved symbol: KIAA1033
Not the approved symbol: DKFZP434B2017
Not the approved symbol: H2AFZ
Not the approved symbol: KIN27
Not the approved symbol: TMEM194A
Not the approved symbol: FAM207A
Not the approved symbol: C19ORF24
Not the approved symbol: HIST1H2BM
Not the approved symbol: C5ORF45
Not the approved symbol: C15ORF57
Not the approved symbol: ATP5H
Not the approved symbol: FAM160B1
Not the approved symbol: PVRL2
Not the approved symbol: SRPR
Not the approved symbol: HN1
Not the approved symbol: SLC9A3R1
Not the approved symbol: 2021-03-08
Not the approved symbol: 00:00:00
Not the approved symbol: H2AFY2
Not the approved symbol: CARS
Not the approved symbol: RQCD1
Not the approved symbol: C12ORF49
Not the approved symbol: SSFA2
Not the approved symbol: 2021-09-15
Not the approved symbol: DKFZP779K1237
Not the approved symbol: GNB2L1
Not the approved symbol: ARHGAP11AB
Not the approved symbol: C21ORF59
Not the approved symbol: ANKRD20A4
Not the approved symbol: HIST1H2BD
Not the approved symbol: C18ORF8
Not the approved symbol: HIST2H2BE
Not the approved symbol: KIAA0100
Not the approved symbol: DSCR3
Not the approved symbol: C14ORF10
Not the approved symbol: WRB
Not the approved symbol: ELMSAN1
Not the approved symbol: TARS
Not the approved symbol: VWA9
Not the approved symbol: UNNAMED
Not the approved symbol: C5ORF30
Not the approved symbol: DDX26B
Not the approved symbol: ANKRD20A2
Not the approved symbol: KIAA1279
Not the approved symbol: HIST3H3
Not the approved symbol: CCNB2V
Not the approved symbol: HCG_39893
Not the approved symbol: C17ORF85
Not the approved symbol: FAM172A
Not the approved symbol: ARMC4
Not the approved symbol: WDR34
Not the approved symbol: HIST2H2BF
Not the approved symbol: HIST1H2BC
Not the approved symbol: WHSC1L1
Not the approved symbol: PHB
Not the approved symbol: SEPTININININ10
Not the approved symbol: ERBB2IP
Not the approved symbol: C4ORF29
Not the approved symbol: C16ORF33
Not the approved symbol: CPSF3L
Not the approved symbol: SLC9A3R2
Not the approved symbol: TMEM206
Not the approved symbol: HIST1H1B
Not the approved symbol: FAM126A
Not the approved symbol: IKBKAP
Not the approved symbol: ERCC5-201
Not the approved symbol: HIST1H1D
Not the approved symbol: RNMTL1
Not the approved symbol: C18ORF21
Not the approved symbol: FAM213A
Not the approved symbol: WDR61
Not the approved symbol: DKFZP686E14208
Not the approved symbol: HIST2H2AC
Not the approved symbol: ATP5A1
Not the approved symbol: L1RE1
Not the approved symbol: PP1187
Not the approved symbol: H1FX
Not the approved symbol: H2AFY
Not the approved symbol: QARS
Not the approved symbol: C10ORF32
Not the approved symbol: FAM21C
Not the approved symbol: H2AFV
Not the approved symbol: DGCR14
Not the approved symbol: COL4A3BP
Not the approved symbol: RLTPR
Not the approved symbol: HN1L
Not the approved symbol: DIEXF
Not the approved symbol: FGFR1OP
Not the approved symbol: ANKRD20A3
Not the approved symbol: TH1L
Not the approved symbol: MRE11A
Not the approved symbol: ADRBK1
Not the approved symbol: C9ORF16
Not the approved symbol: C3ORF17
Not the approved symbol: RNF219
Not the approved symbol: C11ORF30
Not the approved symbol: LASS1
Not the approved symbol: HIST3H2BB
Not the approved symbol: TCEB3
Not the approved symbol: C2ORF44
Not the approved symbol: LEPRE1
Not the approved symbol: WDR60
Not the approved symbol: KARS
Not the approved symbol: TTC30A
Not the approved symbol: DKFZP781C0425
Not the approved symbol: RARS
Not the approved symbol: GCOM2
Not the approved symbol: ZCCHC11
Not the approved symbol: MYEOV2
Not the approved symbol: C4ORF3
Not the approved symbol: ECM29
Not the approved symbol: EPT1
Not the approved symbol: HIST1H2BO
Not the approved symbol: CCDC101
Not the approved symbol: VPRBP
Not the approved symbol: C19ORF43
Not the approved symbol: KIAA1598
Not the approved symbol: MPP5
Not the approved symbol: LPHN2
Not the approved symbol: NHP2L1
Not the approved symbol: IGJ
Not the approved symbol: NUPL2
Not the approved symbol: FAM92A1
Not the approved symbol: LEPREL2
Not the approved symbol: C17ORF80
Not the approved symbol: HIST1H2BN
Not the approved symbol: LINS
Not the approved symbol: KIAA0355
Not the approved symbol: HIST1H2BB
Not the approved symbol: SPACIA2
Not the approved symbol: CRAMP1L
Not the approved symbol: 44M2.3
Not the approved symbol: FAM122B
Not the approved symbol: SPATA5
Not the approved symbol: NIP30
Not the approved symbol: DKFZP564M2223
Not the approved symbol: PIP5K2B
Not the approved symbol: HIST1H2AD
Not the approved symbol: FAM46D
Not the approved symbol: DKFZP586F0420
Not the approved symbol: 2021-03-07
Not the approved symbol: SKIV2L
Not the approved symbol: MTSS1L
Not the approved symbol: CXORF56
Not the approved symbol: SGOL1
Not the approved symbol: TMEM251
Not the approved symbol: FAM195B
Not the approved symbol: NUPL1
Not the approved symbol: GCN1L1
Not the approved symbol: TCTEX1D2
Not the approved symbol: DAK
Not the approved symbol: ZNF724P
Not the approved symbol: SEPTININININ8
Not the approved symbol: ITFG3
Not the approved symbol: WBSCR22
Not the approved symbol: HIST1H1E
Not the approved symbol: HIST1H1C
Not the approved symbol: ZAK
Not the approved symbol: LOH12CR1
Not the approved symbol: IMPAD1
Not the approved symbol: APOA1BP
Not the approved symbol: BAP18
Not the approved symbol: ATP5J
Not the approved symbol: LNP
Not the approved symbol: C11ORF31
Not the approved symbol: LOC81691
Not the approved symbol: TMEM55B
Not the approved symbol: FAM21A
Not the approved symbol: KDELC2
Not the approved symbol: C1ORF123
Not the approved symbol: ATPIF1
Not the approved symbol: SELH
Not the approved symbol: C21ORF33
Not the approved symbol: NAN
Not the approved symbol: ATP5O
Not the approved symbol: TTC26
Not the approved symbol: C10ORF35
Not the approved symbol: CENPJ
Not the approved symbol: CCDC53
Not the approved symbol: HDGFRP2
Not the approved symbol: IARS
Not the approved symbol: HIST1H2BJ
Not the approved symbol: LARS
Not the approved symbol: HNRPLL
Not the approved symbol: FAM208A
Not the approved symbol: KIAA1522
Not the approved symbol: TWISTNB
Not the approved symbol: PRUNE
Not the approved symbol: SGOL2
Not the approved symbol: SEPTININININ7
Not the approved symbol: KIAA1524
Not the approved symbol: HIST1H2AH
Not the approved symbol: DKFZP781P1017
Not the approved symbol: UHRF1BP1L
Not the approved symbol: ASNA1
Not the approved symbol: DKFZP781D1416
Not the approved symbol: FAM134B
Not the approved symbol: BVES
Not the approved symbol: C4ORF32
Not the approved symbol: 2021-03-06
Not the approved symbol: SEPTININININ6
Not the approved symbol: CIRH1A
Not the approved symbol: AGPAT6
Not the approved symbol: TTC37
Not the approved symbol: HIST2H2AB
Not the approved symbol: TMEM199
Not the approved symbol: SPG20
Not the approved symbol: FAM109A
Not the approved symbol: METTL7A
Not the approved symbol: HIST2H3A
Not the approved symbol: FAM192A
Not the approved symbol: H1F0
Not the approved symbol: FAM195A
Not the approved symbol: MPP6
Not the approved symbol: SSSCA1
Not the approved symbol: FAM73B
Not the approved symbol: C11ORF57
Not the approved symbol: PAPD4
Not the approved symbol: HIST1H2AJ
Not the approved symbol: H2BFS
Not the approved symbol: FAM179B
Not the approved symbol: HIST1H2BH
Not the approved symbol: ORAOV1
Not the approved symbol: MINA
Not the approved symbol: HSPB11
Not the approved symbol: IXL
Not the approved symbol: KIAA0196
Not the approved symbol: C21ORF2
Not the approved symbol: FAM134A
Not the approved symbol: FAM101B
Not the approved symbol: HIST1H3A
Not the approved symbol: UHRF1BP1
Not the approved symbol: SEPTININININ2
Not the approved symbol: WDR92
Not the approved symbol: TCEB1
Not the approved symbol: C20ORF24
Not the approved symbol: GYLTL1B
Not the approved symbol: DKFZP686E0752
Not the approved symbol: CD3EAP
Not the approved symbol: TNRC11
Not the approved symbol: CGI-87
Not the approved symbol: C8ORF59
Not the approved symbol: CASC4
Not the approved symbol: C10ORF32-ASMT
Not the approved symbol: C17ORF53
Not the approved symbol: KIAA1429
Not the approved symbol: C1ORF131
Not the approved symbol: ASUN
Not the approved symbol: HDGFRP3
Not the approved symbol: SELT
Not the approved symbol: SOGA3
Not the approved symbol: C17ORF62
Not the approved symbol: PAP1
Not the approved symbol: EIF2S3L
Not the approved symbol: HIST1H4A
Not the approved symbol: CD97
Not the approved symbol: DKFZP566H1924
Not the approved symbol: KIAA1211
Not the approved symbol: H2AFJ
Not the approved symbol: FAM45B
Not the approved symbol: C6ORF10
Not the approved symbol: KIAA0020
Not the approved symbol: MKL2
Not the approved symbol: C18ORF25
Not the approved symbol: C13ORF34
Not the approved symbol: LEPREL4
Not the approved symbol: CCDC115
Not the approved symbol: C14ORF1
Not the approved symbol: VARS
Not the approved symbol: KIAA0430
Not the approved symbol: FAM126B
Not the approved symbol: RFWD2
Not the approved symbol: UFD1L
Not the approved symbol: KIF1BP
Not the approved symbol: SOGA1

          Input Approved symbol
0      FLJ00186             NaN
1    PMF1-BGLAP      PMF1-BGLAP
2  DKFZP434D199             NaN
3        DDX12P          DDX12P
4         AKAP2           AKAP2

Number of interactions: 30096

  target_gene_name_approved interactor_gene_name_approved     gene_pair
0                      AAMP                        ARGLU1   AAMP:ARGLU1
1                      AAMP                       CWF19L2  AAMP:CWF19L2
2                      AAMP                       PRPF40A  AAMP:PRPF40A
3                      AAMP                         RPL10    AAMP:RPL10
4                      AAMP                         RSRC1    AAMP:RSRC1

In [ ]:
# Merge all literature interactomes (this should be the "literature-PPI" list used in the main text, which is the union of all literature PPIs from HINT, BioPlex and OpenCell, with gene pairs using the approved HGNC symbols)

HINT_all_interactome = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/HINT/HomoSapiens_both_all.txt"))[["Gene_approved_A", "Gene_approved_B", "gene_pair"]].rename(columns={"Gene_approved_A":"gene_A", "Gene_approved_B":"gene_B"})
bioplex_all_interactome = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/BioPlex/BioPlex_all.tsv"))[["SymbolA_approved", "SymbolB_approved", "gene_pair"]].rename(columns={"SymbolA_approved":"gene_A", "SymbolB_approved":"gene_B"})
opencell_interactome = pd.read_table(os.path.join(root_dir, "_DATA/_COMMON/network/OpenCell/opencell_all.csv"), sep=',')[["target_gene_name_approved", "interactor_gene_name_approved", "gene_pair"]].rename(columns={"target_gene_name_approved":"gene_A", "interactor_gene_name_approved":"gene_B"})

# !! Issue: many genes might be the previous symbols and not the approved HGNC symbols
literature_all_interactome = pd.concat([HINT_all_interactome, bioplex_all_interactome, opencell_interactome], axis=0).drop_duplicates(subset=["gene_pair"]).reset_index(drop=True)
literature_all_interactome.to_csv(os.path.join(root_dir, "_DATA/_COMMON/network/all_literature/literature_all.txt"), sep='\t', index=None)
print("Number of interactions:", len(literature_all_interactome))
literature_all_interactome.head()

Number of interactions: 765276

     gene_A gene_B       gene_pair
0     WDR77   RIN3      RIN3:WDR77
1  PAFAH1B3  LRRK2  LRRK2:PAFAH1B3
2      UBA1  LRRK2      LRRK2:UBA1
3      THRB  HDAC3      HDAC3:THRB
4      THRB  NCOR1      NCOR1:THRB